# Generated by Django 5.0.6 on 2024-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_description_remove_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datebirth',
            field=models.DateField(null=True),
        ),
    ]
